### ISSUE TITLE
Magicsigns 1.4.1 doesnt load signs when server starts

### ISSUE THREAD

**Issue by Gotxi** [Philipp15b/MagicSigns#9]
Hi! Im trying to use magicsigns to use command signs. Everything works fine until i stop the server. This is what i do:

1) Make a command sign with this:
[command]
/say hello

2) right click, signs works fine, the server says hello

3) /stop, server stops fine

4) I check everything is saved correctly, this is the content of signs.db.yml, i dont see my /say hello in here (github is not respecting the tabs):

magic-signs:
- ==: de.philworld.bukkit.magicsigns.config.MagicSignSerializationProxy
  type: de.philworld.bukkit.magicsigns.signs.command.CommandSign
  z: 7
  y: 57
  world: palace
  x: -35

5) start the server again, magicsigns gives this error:

2013-04-10 01:22:08 [INFO] [MagicSigns] Enabling MagicSigns v1.4.1
2013-04-10 01:22:08 [SEVERE] [MagicSigns] Error loading Magic Sign from config: null
java.lang.NullPointerException
    at de.philworld.bukkit.magicsigns.config.MagicSignSerializationProxy.getMagicSign(MagicSignSerializationProxy.java:127)
    at de.philworld.bukkit.magicsigns.MagicSigns.loadSigns(MagicSigns.java:226)
    at de.philworld.bukkit.magicsigns.MagicSigns.onEnable(MagicSigns.java:159)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
    at org.bukkit.craftbukkit.v1_5_R2.CraftServer.loadPlugin(CraftServer.java:305)
    at org.bukkit.craftbukkit.v1_5_R2.CraftServer.enablePlugins(CraftServer.java:287)
    at net.minecraft.server.v1_5_R2.MinecraftServer.j(MinecraftServer.java:309)
    at net.minecraft.server.v1_5_R2.MinecraftServer.e(MinecraftServer.java:288)
    at net.minecraft.server.v1_5_R2.MinecraftServer.a(MinecraftServer.java:248)
    at net.minecraft.server.v1_5_R2.DedicatedServer.init(DedicatedServer.java:154)
    at net.minecraft.server.v1_5_R2.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.v1_5_R2.ThreadServerApplication.run(SourceFile:573)
2013-04-10 01:22:08 [INFO] [MagicSigns] Using Vault for economy.
2013-04-10 01:22:08 [INFO] [MagicSigns] Using Vault for permissions.

6) The sign doesn't work anymore. From here if i do a /reload, the file signs.db.yml "resets" itself and its content is now:
magic-signs: []

Anything i can do? Thanks in advanced :)

**Comment by Philipp15b** [comment]
Thanks for reporting this issue. I do not know why this happens, this is impossible with the default CraftBukkit, except after removing a world.

Anyways, the code that this happens in will be removed in the next version of MagicSigns as it is generally not optimal performance-wise and may lead to bugs (although not this one).

In the meantime, which Bukkit implementation do you use? Do you use any plugins such as Multiverse?

**Comment by Gotxi** [comment]
Hi! thanks for the fast response :D

Im using spigot, this is my /version output:

14:03:27 [INFO] This server is running CraftBukkit version git-Spigot-763 (MC: 1.5.1) (Implementing API version 1.5.1-R0.2-SNAPSHOT)

And yes, i use "my worlds" plugin, this is the list of all my active plugins:

14:04:44 [INFO] [PlugMan] Plugins: AntiCheat v1.5.7, BanHammer v2.1.0, BetterCombat v0.6, BKCommonLib v1.51, BookRules v2.0, ChestFix v0.9, CoreProtect v2.05, CraftBukkitUpToDate v3.0.3, EntityManager v5.1.2, Essentials v2.10.1, EssentialsSpawn v2.10.1, FAntiXRay v2.6, GiantCaves v2.2, GriefPrevention v7.7, HealthBar v1.1, Jobs v2.10.0.beta1, KBPL v1.0.3, Lockette v1.7.9, LogIt v0.4.3, Loot v3.2.0, MagicSigns v1.4.1, MegaCatch v1.0.1, MineBackup v5.9.4, More-Mobs v1.7.3, My Worlds v1.6, PerformanceMonitor v1.7.0, PermissionFinder v1.2.2, PlugMan v1.8.3, ProtocolLib v2.4.1, QuickShop v4.0, QuickSwap v1.0, RealChop v0.08, Shield v1.8.2, Shopkeepers v1.13, SignCopy v0.4, SQLibrary v4.2, TimingsParser v0.1, TorchThrow v0.1, Vault v1.2.24-b304, VillagerNames v0.3, WorldEdit v5.5.5, YAPP v1.3

**Comment by Philipp15b** [comment]
I could not reproduce the problem and I still don't really know why this issue happens for you... But I'm fairly sure I fixed it with bf1b4e24b339d43fd6ca45c64750d310f39c964f :grin: If this issue appears to you even after the next release of MagicSigns, please report back here.
